### ISSUE TITLE
ParseError: Unexpected token

### ISSUE THREAD

**Issue by trusktr** [davidguttman/cssify#22]
I've a file that imports css like this:

```js
import 'famous/core/famous.css'
import 'highlight.js/styles/solarized_light.css'
```

The `famous.css` file gets loaded just fine, but the second css file fails on the first character (a `.`).

solarized_light.css begins like this:

```css
/*

Orginal Style from ethanschoonover.com/solarized (c) Jeremy Hull <sourdrums@gmail.com>

*/

.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #fdf6e3;
  color: #657b83;
  -webkit-text-size-adjust: none;
}
```

I've got the following transforms:

```js
                  browserify.add(appFile)
                    .transform(to5ify)
                    .transform(famousify)
                    .transform(cssify)
                    .bundle(function(err, app) { ... }
```

and I'm getting this error:

```
Error: Error bundling app file /Users/josephpea/src/trusktr+readem/src/ejs/js/app.js.
/Users/josephpea/src/trusktr+readem/node_modules/highlight.js/styles/solarized_light.css:7
.hljs {
^
ParseError: Unexpected token
    at Labeled.<anonymous> (/Users/josephpea/src/trusktr+readem/bin/read'em.js:164:40)
    at Labeled.emit (events.js:95:17)
    at Labeled.<anonymous> (/Users/josephpea/src/trusktr+readem/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
    at Labeled.emit (events.js:117:20)
    at DestroyableTransform.<anonymous> (/Users/josephpea/src/trusktr+readem/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:132:18)
    at DestroyableTransform.emit (events.js:95:17)
    at DestroyableTransform._transform (/Users/josephpea/src/trusktr+readem/node_modules/browserify/index.js:621:30)
    at DestroyableTransform.Transform._read (/Users/josephpea/src/trusktr+readem/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/josephpea/src/trusktr+readem/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at Labeled.Pipeline._write (/Users/josephpea/src/trusktr+readem/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/index.js:72:22)
```

Any idea what might be happening?
